### ISSUE TITLE
Build errors on Raspbian Stretch (RPi3)

### ISSUE THREAD

**Issue by mrgw454** [mizapf/tiimagetool#2]
Hi Michael,

I'm trying to build/compile tiimagetool on Raspbian Stretch.  I thought I had all dependencies met, but getting this error during the build process:

tipi@tipi:~/source/tiimagetool $ ant dist
Buildfile: /home/tipi/source/tiimagetool/build.xml

init:

tiimagetool:
     [echo] 
     [echo]      ****    Building TIImageTool  ****
     [echo]    
    [javac] Compiling 138 source files to /home/tipi/source/tiimagetool/build
    [javac] warning: [options] bootstrap class path not set in conjunction with -source 1.7
    [javac] /home/tipi/source/tiimagetool/src/de/mizapf/timt/TIImageTool.java:488: error: cannot find symbol
    [javac] 				gnu.io.DriverManager.getInstance().loadDrivers();
    [javac] 				      ^
    [javac]   symbol:   class DriverManager
    [javac]   location: package gnu.io
    [javac] 1 error
    [javac] 1 warning

BUILD FAILED
/home/tipi/source/tiimagetool/build.xml:36: Compile failed; see the compiler error output for details.

Total time: 9 seconds

Any help would be appreciated and thank you!

**Comment by mrgw454** [comment]
I do have the RXTXcomm.jar in the appropriate folder:

tipi@tipi:~/source/tiimagetool/ext $ ls -l
total 64
-rw-r--r-- 1 tipi tipi    90 Jun 26 11:19 README
-rw-r--r-- 1 tipi tipi 61087 Jul 26  2014 RXTXcomm.jar

**Comment by mizapf** [comment]
Ah ... **DriverManager.** I remember. If you check with jar tvf RXTXcomm.jar, you will probably miss that class. The author of RXTX has committed a new release, refactoring a lot of code. And I also remember that it was still buggy, but I lost it out of sight since January.

Download this version of RXTX: http://www.mizapf.eu/files/RXTXcomm.jar

**Comment by mrgw454** [comment]
Hi Michael,

This worked perfectly!

tipi@tipi:~/source/tiimagetool $ ant
Buildfile: /home/tipi/source/tiimagetool/build.xml

init:

tiimagetool:
     [echo] 
     [echo]      ****    Building TIImageTool  ****
     [echo]    
    [javac] Compiling 138 source files to /home/tipi/source/tiimagetool/build
    [javac] warning: [options] bootstrap class path not set in conjunction with -source 1.7
    [javac] 1 warning
     [copy] Copying 27 files to /home/tipi/source/tiimagetool/build/de/mizapf/timt/ui
     [copy] Copying 3 files to /home/tipi/source/tiimagetool/build/de/mizapf/timt/util

distri:
    [mkdir] Created dir: /home/tipi/source/tiimagetool/dist/lib
      [jar] Building jar: /home/tipi/source/tiimagetool/dist/lib/tiimagetool.jar

dist:

BUILD SUCCESSFUL
Total time: 13 seconds

Thank you so much for your quick response!

**Comment by mizapf** [comment]
Good. The serial support may still not run with your configuration because you need the native library. 

By the way, this version of RXTX is on Github, and this was the main reason why I switched to it; the original version has not been maintained for the last 10 years. But there are still many issues with this refurbished version, and I contacted the author early in January. We made it compile, and I completely forgot about it. This needs to be continued some day.

**Comment by mizapf** [comment]
I suppose we can close this issue?

**Comment by mrgw454** [comment]
Yes, sir and thank you!
